# docker compose -f docker-compose.stage.yml up --build -d --force-recreate
# docker compose -f docker-compose.stage.yml down -v --rmi local
version: '0.1'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8010:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./privkey.pem:/etc/nginx/privkey.pem
      - ./cert.pem:/etc/nginx/cert.pem
    restart: always
  server:
    image: moon-zip-backend
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - '${REDIS_PORT}:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis:/data
volumes:
  db:
  redis:
