# docker compose -f docker-compose.dev.yml up --build --force-recreate -d
# docker compose -f docker-compose.dev.yml down -v --rmi local
version: '0.1'

services:
  server:
    image: moon-zip-backend
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    restart: always
    ports:
      - '8010:3000'
