# docker compose -f docker-compose.stage.yml up --build --force-recreate
# docker compose -f docker-compose.stage.yml down -v --rmi local
version: '0.1'

services:
  server:
    image: moon-zip-backend
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    restart: always
    ports:
      - '8010:3000'
    volumes:
      - .:/usr/src/app
      - server:/usr/src/app/node_modules
    depends_on:
      - db
      - redis
  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=Asia/Seoul
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - '${REDIS_PORT}:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TZ=Asia/Seoul
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
volumes:
  server:
  db_data:
  redis_data:
