# docker compose -f docker-compose.stage.yml up --build -d --force-recreate
# docker compose -f docker-compose.stage.yml down -v --rmi local --remove-orphans --timeout 0
version: '0.1'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8010:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./privkey.pem:/etc/nginx/privkey.pem
      - ./fullchain.pem:/etc/nginx/fullchain.pem
    restart: always
    environment:
      - TZ=Asia/Seoul
  server:
    image: moon-zip-backend
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - /usr/src/logs:/usr/src/app/logs
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - db
      - redis-jwt
      - redis-cache
  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=Asia/Seoul
    volumes:
      - db:/var/lib/postgresql/data
  redis-jwt:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_JWT_PASSWORD}
      - TZ=Asia/Seoul
    command: ["redis-server", "--requirepass", "${REDIS_JWT_PASSWORD}"]
    volumes:
      - jwt-server:/data
  redis-cache:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_CACHE_PASSWORD}
      - TZ=Asia/Seoul
    command: ["redis-server", "--requirepass", "${REDIS_CACHE_PASSWORD}"]
    volumes:
      - cache-server:/data
volumes:
  db:
  jwt-server:
  cache-server:
