# docker compose -f docker-compose.dev.yml up --build --force-recreate
# docker compose -f docker-compose.dev.yml down -v --rmi local
version: '0.1'

services:
  server:
    image: moon-zip-backend
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      target: development
    command: npm run ${cmd:-start:dev}
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - server:/usr/src/app/node_modules
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - db
      - redis
  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=Asia/Seoul
  redis:
    image: redis:latest
    ports:
      - '${REDIS_PORT}:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TZ=Asia/Seoul
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
volumes:
  server:

