name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

jobs:

  build:
    name: build-deploy
    runs-on: ubuntu-latest

    steps:
      - name: deploy using ssh
        env:
          RASP_DATABASE_URL: ${{ secrets.RASP_DATABASE_URL }}
          RASP_SSL_PATH: ${{ secrets.RASP_SSL_PATH }}
          PRIVATE_ACCESS_TOKEN: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RASP_HOST }}
          username: ${{ secrets.RASP_USERNAME }}
          password: ${{ secrets.RASP_PASSWORD }}
          port: ${{ secrets.RASP_PORT }}
          envs: RASP_DATABASE_URL,PRIVATE_ACCESS_TOKEN,RASP_SSL_PATH,JWT_SECRET,REDIS_HOST,REDIS_PORT,REDIS_PASSWORD
          script: |
            set -e
            cd /usr/src
            if [ -d 'moon-zip-backend' ]; then
              cd moon-zip-backend
              sudo docker compose -f docker-compose.stage.yml stop server
              if sudo docker volume ls -q | grep -q 'moon-zip-backend_server'; then
                sudo docker compose -f docker-compose.stage.yml rm -f -v server
              fi
              cd ../
              sudo rm -rf moon-zip-backend
            fi

            sudo git clone https://giwonn:$PRIVATE_ACCESS_TOKEN@github.com/moon-zip/moon-zip-backend.git
            cd moon-zip-backend
            git config --global --add safe.directory /usr/src/moon-zip-backend
            cd ../
            sudo echo "DATABASE_URL=\"${RASP_DATABASE_URL}\"" > ".env"
            sudo echo "RASP_SSL_PATH=\"${RASP_SSL_PATH}\"" >> ".env"
            sudo echo "JWT_SECRET=\"${JWT_SECRET}\"" >> ".env"
            sudo echo "REDIS_HOST=\"${REDIS_HOST}\"" >> ".env"
            sudo echo "REDIS_PORT=\"${REDIS_PORT}\"" >> ".env"
            sudo echo "REDIS_PASSWORD=\"${REDIS_PASSWORD}\"" >> ".env"
            sudo mv .env moon-zip-backend/
            
            sudo cp $RASP_SSL_PATH/privkey.pem moon-zip-backend
            sudo cp $RASP_SSL_PATH/fullchain.pem moon-zip-backend

            cd moon-zip-backend
            sudo git pull origin develop
            sudo git checkout develop
            sudo docker compose -f docker-compose.stage.yml up --build --force-recreate -d server
            sudo docker compose -f docker-compose.stage.yml up -d --force-recreate nginx
