name: Docker Image CI

on:
  pull_request:
    branches: [ "develop" ]
  push:
    branches: [ "develop" ]

jobs:

  build:
    name: build-deploy
    runs-on: ubuntu-latest

    steps:
      - name: deploy using ssh
        env:
          RASP_DATABASE_URL: ${{ secrets.RASP_DATABASE_URL }}
          PRIVATE_ACCESS_TOKEN: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RASP_HOST }}
          username: ${{ secrets.RASP_USERNAME }}
          password: ${{ secrets.RASP_PASSWORD }}
          port: ${{ secrets.RASP_PORT }}
          envs: RASP_DATABASE_URL,PRIVATE_ACCESS_TOKEN
          script: |
            set -e
            cd /usr/src
            if [ ! -d 'moon-zip-backend' ]; then
              sudo git clone https://giwonn:$PRIVATE_ACCESS_TOKEN@github.com/moon-zip/moon-zip-backend.git
              cd moon-zip-backend
              sudo echo "DATABASE_URL="$RASP_DATABASE_URL > ".env"
              cd ../
            fi
            cd moon-zip-backend
            git pull origin develop
            git checkout develop
            docker compose -f docker-compose.dev.yml up --build --force-recreate -d
