name: Docker Image CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:

  build:
    name: build-deploy
    runs-on: ubuntu-latest

    steps:
      - name: deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RASP_HOST }}
          username: ${{ secrets.RASP_USERNAME }}
          password: ${{ secrets.RASP_PASSWORD }}
          port: ${{ secrets.RASP_PORT }}
          script: |
            sudo cd /usr/src
            if [ ![ -d "moon-zip-backend" && -e "moon-zip-backend" ] ]; then
              sudo git clone git@github.com:moon-zip/moon-zip-backend.git
              cd moon-zip-backend
              echo `DATABASE_URL=${{ secrets.RASP_DATABASE_URL }}` > ".env"
              cd ../
            fi
            sudo ./deploy-develop.sh
